title: Jarmanitor Blog
author: Oleg Jarma Montoya
description: I put a lot of effort on things that don't really matter. This is a small blog to document that
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme 