title: Jarmanitor Blog
author: Oleg Jarma Montoya
description: I put a lot of effort on things that don't really matter. This is a small blog to document that
theme: minima
minima:
  skin: dark

header_pages:
  - about.md
  - projects.md